site_name: Dasset
pages:
  - Home: index.md
  - About: about.md
  - BAO: bao.md
  - BAS: bas.md
  - Whitepaper: whitepaper.md
  - POC:
    - Badge: 'poc/badge.md'
    - PDAMP: 'poc/pdamp.md'
  - Misc: misc.md
theme: readthedocs    
